### ISSUE TITLE
Wifi state is not persisted

### ISSUE THREAD

**Issue by mstoffel-sag** [thin-edge/tedge-rugpi-image#69] opened 2024-02-12 09:44 UTC
After flashing an image to my PI3b (regardless with or without wifi enable) i can configure wifi just fine and it works after reboot. 

After doing a OTA Firmware Update the state of the wifi interface is always disabled:

3: wlan0: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN group default qlen 1000
    link/ether b8:27:eb:0c:32:55 brd ff:ff:ff:ff:ff:ff
root@rpi3-b827eb596700 ~ # nmcli radio wifi
disabled

**Comment by reubenmiller** [comment] 2024-02-17 00:27
Tracked down the issue. Root cause was the base raspberry pi OS image includes a default software killswitch for the wifi on Raspberry Pi 3 and 4 devices (maybe 5 as well, but a bit unclear). The logic was associated with switching off 5GHz when the country code is not specified (which is isn't in our images as we want these to be generic).

Fixed by a PR in the tedge-rugpi-core respository, https://github.com/thin-edge/tedge-rugpi-core/pull/18

You should be able to test it out from >= [20240217.0110](https://github.com/thin-edge/tedge-rugpi-image/releases/tag/20240217.0110)

**Closed** 2024-02-19 10:18 UTC
